(ischar (strftime ("%%%n%t%H%I%k%l", localtime (time ())))
 && ischar (strftime ("%M%p%r%R%s%S%T", localtime (time ())))
 && ischar (strftime ("%X%Z%z%a%A%b%B", localtime (time ())))
 && ischar (strftime ("%c%C%d%e%D%h%j", localtime (time ())))
 && ischar (strftime ("%m%U%w%W%x%y%Y", localtime (time ()))))
